# -*- coding: utf-8 -*-
"""Gera FRASES EM INGLÊS COM TRADUÇÃO em assets/frases/.
index.json (categorias) + {id}.json = [{"t": inglês, "r": tradução}, ...].
Frases autorais/curtas (sem depender de citações protegidas)."""
import json, os

BASE = os.path.join(os.path.dirname(__file__), "..", "assets", "frases")
os.makedirs(BASE, exist_ok=True)

CATS = [
    ("amor",       "Love · Amor",           "❤️", ["#667EEA", "#764BA2"]),
    ("curtas",     "Short · Curtas",        "✂️", ["#4776E6", "#8E54E9"]),
    ("motivacao",  "Motivation · Motivação","🚀", ["#396afc", "#2948ff"]),
    ("sucesso",    "Success · Sucesso",     "🏆", ["#5B247A", "#1BCEDF"]),
    ("atitude",    "Attitude · Atitude",    "😎", ["#41295a", "#2F0743"]),
    ("vida",       "Life · Vida",           "🌎", ["#2193b0", "#6dd5ed"]),
    ("superacao",  "Strength · Superação",  "💪", ["#7F00FF", "#E100FF"]),
    ("tristes",    "Sad · Tristes",         "💔", ["#141E30", "#243B55"]),
    ("status",     "Status",                "💬", ["#4568DC", "#B06AB3"]),
    ("sabedoria",  "Wisdom · Sabedoria",    "🧠", ["#360033", "#0b8793"]),
]

def q(t, r): return {"t": t, "r": r}

DATA = {
"amor": [
q("You are my favorite hello and my hardest goodbye.", "Você é o meu 'oi' favorito e o meu adeus mais difícil."),
q("With you, every day feels like the first one.", "Com você, todo dia parece o primeiro."),
q("My heart is, and always will be, yours.", "Meu coração é, e sempre será, seu."),
q("You are the reason I believe in love.", "Você é a razão de eu acreditar no amor."),
q("Home is wherever I'm with you.", "Lar é onde quer que eu esteja com você."),
q("I choose you, today and every day.", "Eu escolho você, hoje e todos os dias."),
q("You are my once in a lifetime.", "Você é o meu uma vez na vida."),
q("Loving you is the easiest thing I've ever done.", "Amar você é a coisa mais fácil que eu já fiz."),
q("You are my sun on the cloudiest days.", "Você é o meu sol nos dias mais nublados."),
q("Every love song makes sense because of you.", "Toda música de amor faz sentido por causa de você."),
q("You are the best thing that ever happened to me.", "Você é a melhor coisa que já me aconteceu."),
q("My favorite place is next to you.", "Meu lugar favorito é ao seu lado."),
q("You make my heart smile.", "Você faz meu coração sorrir."),
q("I found forever the day I found you.", "Eu encontrei o 'para sempre' no dia em que te encontrei."),
q("You are my today and all of my tomorrows.", "Você é o meu hoje e todos os meus amanhãs."),
q("In a room full of people, my eyes will always search for you.", "Numa sala cheia de gente, meus olhos sempre vão procurar você."),
q("You are my calm and my adventure.", "Você é a minha calma e a minha aventura."),
q("I love you more than words can say.", "Eu te amo mais do que as palavras conseguem dizer."),
q("You are the poem my heart writes alone.", "Você é o poema que meu coração escreve sozinho."),
q("Being with you is my favorite place to be.", "Estar com você é o meu lugar favorito."),
q("You are proof that soulmates are real.", "Você é a prova de que almas gêmeas existem."),
q("My heart recognized you before I understood why.", "Meu coração te reconheceu antes de eu entender o porquê."),
q("You are the missing piece I never knew I needed.", "Você é a peça que faltava e que eu nem sabia que precisava."),
q("Forever is not long enough with you.", "O 'para sempre' não é longo o bastante com você."),
q("You are my favorite reason to lose sleep.", "Você é o meu motivo favorito pra perder o sono."),
q("I fall for you a little more every day.", "Eu me apaixono por você um pouco mais a cada dia."),
q("You are my heart's best decision.", "Você é a melhor decisão do meu coração."),
q("Your smile is my favorite view.", "Seu sorriso é a minha vista favorita."),
q("I want all of my lasts to be with you.", "Eu quero que todas as minhas últimas vezes sejam com você."),
q("You are the love I waited my whole life for.", "Você é o amor que eu esperei a vida toda."),
],
"curtas": [
q("Stay wild.", "Continue selvagem."),
q("Less perfect, more real.", "Menos perfeito, mais real."),
q("Good vibes only.", "Só as boas energias."),
q("Be your own hero.", "Seja seu próprio herói."),
q("Chase the sun.", "Persiga o sol."),
q("Love louder.", "Ame mais alto."),
q("Keep it simple.", "Mantenha simples."),
q("Dream big.", "Sonhe grande."),
q("Choose joy.", "Escolha a alegria."),
q("Never look back.", "Nunca olhe para trás."),
q("Just breathe.", "Apenas respire."),
q("Stay golden.", "Continue dourado."),
q("Find your fire.", "Encontre o seu fogo."),
q("Be the light.", "Seja a luz."),
q("Live for now.", "Viva o agora."),
q("Trust the timing.", "Confie no tempo certo."),
q("Wander often.", "Perca-se com frequência."),
q("Bloom anyway.", "Floresça mesmo assim."),
q("Rise and shine.", "Levante e brilhe."),
q("Enjoy the little things.", "Aproveite as pequenas coisas."),
q("Make it happen.", "Faça acontecer."),
q("Stay true.", "Seja verdadeiro."),
q("Feel it all.", "Sinta tudo."),
q("Own your story.", "Seja dono da sua história."),
q("Keep going.", "Continue seguindo."),
q("Be fearless.", "Seja destemido."),
q("Create your sunshine.", "Crie o seu próprio sol."),
q("Let it be.", "Deixe acontecer."),
q("Do more of what you love.", "Faça mais do que você ama."),
q("Shine on.", "Continue brilhando."),
],
"motivacao": [
q("Start where you are, use what you have.", "Comece onde você está, use o que você tem."),
q("Small steps every day lead to big changes.", "Pequenos passos todo dia levam a grandes mudanças."),
q("Your only limit is you.", "Seu único limite é você."),
q("Discipline beats motivation.", "Disciplina vence a motivação."),
q("Progress, not perfection.", "Progresso, não perfeição."),
q("Do it now. Later becomes never.", "Faça agora. O 'depois' vira nunca."),
q("You didn't come this far to only come this far.", "Você não chegou até aqui pra parar aqui."),
q("Work hard in silence, let success make the noise.", "Trabalhe duro no silêncio, deixe o sucesso fazer o barulho."),
q("Believe you can and you're halfway there.", "Acredite que consegue e já está na metade do caminho."),
q("Push yourself, because no one else will do it for you.", "Cobre de si mesmo, porque ninguém fará isso por você."),
q("Great things never come from comfort zones.", "Grandes coisas nunca vêm de zonas de conforto."),
q("Dream it. Wish it. Do it.", "Sonhe. Deseje. Faça."),
q("Fall seven times, stand up eight.", "Caia sete vezes, levante oito."),
q("The best way out is always through.", "A melhor saída é sempre atravessar."),
q("Wake up with determination, go to bed with satisfaction.", "Acorde com determinação, durma com satisfação."),
q("Don't watch the clock; do what it does — keep going.", "Não olhe o relógio; faça o que ele faz — siga em frente."),
q("Success is the sum of small efforts repeated daily.", "O sucesso é a soma de pequenos esforços repetidos diariamente."),
q("Your future is created by what you do today.", "Seu futuro é criado pelo que você faz hoje."),
q("Turn your wounds into wisdom.", "Transforme suas feridas em sabedoria."),
q("Difficult roads often lead to beautiful destinations.", "Estradas difíceis costumam levar a destinos lindos."),
q("Stay focused and never give up.", "Mantenha o foco e nunca desista."),
q("The comeback is always stronger than the setback.", "A volta por cima é sempre mais forte que a queda."),
q("Be stronger than your excuses.", "Seja mais forte que as suas desculpas."),
q("One day or day one. You decide.", "Um dia ou dia um. Você decide."),
q("Doubt kills more dreams than failure ever will.", "A dúvida mata mais sonhos do que o fracasso jamais matará."),
q("Make today so awesome yesterday gets jealous.", "Faça o hoje tão incrível que o ontem fique com inveja."),
q("You are capable of amazing things.", "Você é capaz de coisas incríveis."),
q("Focus on the step in front of you, not the whole staircase.", "Foque no degrau à sua frente, não na escada inteira."),
q("Hustle until your haters ask if you're hiring.", "Trabalhe até seus invejosos perguntarem se você está contratando."),
q("Prove them wrong.", "Prove que eles estão errados."),
],
"sucesso": [
q("Success is not final, failure is not fatal.", "O sucesso não é definitivo, o fracasso não é fatal."),
q("Winners focus on winning, losers focus on winners.", "Vencedores focam em vencer, perdedores focam nos vencedores."),
q("Don't stop when you're tired. Stop when you're done.", "Não pare quando estiver cansado. Pare quando terminar."),
q("Money grows where attention flows.", "O dinheiro cresce onde a atenção flui."),
q("Be so good they can't ignore you.", "Seja tão bom que não possam te ignorar."),
q("Success loves preparation.", "O sucesso ama a preparação."),
q("Your network is your net worth.", "Sua rede de contatos é o seu patrimônio."),
q("Invest in yourself. It pays the best interest.", "Invista em si mesmo. Rende os melhores juros."),
q("Consistency is what turns average into excellence.", "A consistência transforma o comum em excelência."),
q("Winners make it happen. Losers let it happen.", "Vencedores fazem acontecer. Perdedores deixam acontecer."),
q("Dream big, start small, act now.", "Sonhe grande, comece pequeno, aja agora."),
q("Opportunities don't happen, you create them.", "Oportunidades não acontecem, você as cria."),
q("The harder you work, the luckier you get.", "Quanto mais você trabalha, mais sorte você tem."),
q("Don't wish for it, work for it.", "Não deseje, trabalhe por isso."),
q("Success is built on the days no one claps.", "O sucesso é construído nos dias em que ninguém aplaude."),
q("Aim for the moon. Even if you miss, you'll land among stars.", "Mire na lua. Mesmo errando, você cai entre as estrelas."),
q("Excuses don't build empires.", "Desculpas não constroem impérios."),
q("Level up. Every single day.", "Evolua. Todos os dias."),
q("If it doesn't challenge you, it won't change you.", "Se não te desafia, não te muda."),
q("Success is the best revenge.", "O sucesso é a melhor vingança."),
q("Build your dreams, or someone will hire you to build theirs.", "Construa seus sonhos, ou alguém vai te contratar pra construir os dele."),
q("Winners train, losers complain.", "Vencedores treinam, perdedores reclamam."),
q("Discipline is the bridge between goals and results.", "A disciplina é a ponte entre metas e resultados."),
q("Stay hungry, stay humble.", "Continue faminto, continue humilde."),
q("Your only competition is who you were yesterday.", "Sua única competição é quem você era ontem."),
],
"atitude": [
q("I'm not lucky, I'm focused.", "Eu não tenho sorte, eu tenho foco."),
q("Be a voice, not an echo.", "Seja uma voz, não um eco."),
q("Confidence is my best outfit.", "Confiança é a minha melhor roupa."),
q("I don't follow trends, I set them.", "Eu não sigo tendências, eu as crio."),
q("Know your worth, then add tax.", "Saiba o seu valor, depois some os impostos."),
q("Less talk, more action.", "Menos conversa, mais ação."),
q("I'm the energy I attract.", "Eu sou a energia que eu atraio."),
q("Classy, never trashy.", "Elegante, nunca vulgar."),
q("Not everyone's cup of tea? Good, I'm champagne.", "Não sou o chá de todo mundo? Ótimo, sou champanhe."),
q("Make them wonder why you're still smiling.", "Faça se perguntarem por que você ainda está sorrindo."),
q("I'm a limited edition.", "Eu sou uma edição limitada."),
q("Silence is my loudest answer.", "O silêncio é a minha resposta mais alta."),
q("Do it with passion or not at all.", "Faça com paixão ou não faça."),
q("Born to stand out.", "Nascido pra se destacar."),
q("My vibe attracts my tribe.", "Minha vibe atrai a minha tribo."),
q("I glow different when I'm happy.", "Eu brilho diferente quando estou feliz."),
q("Be the type of energy people crave.", "Seja o tipo de energia que as pessoas desejam."),
q("Underestimate me. That'll be fun.", "Me subestime. Vai ser divertido."),
q("I'm not for everyone, and that's fine.", "Eu não sou pra todo mundo, e tudo bem."),
q("Stay real. Fake is exhausting.", "Seja real. Ser falso cansa."),
q("Prove yourself to yourself, not to others.", "Prove seu valor pra você, não pros outros."),
q("Good things happen to those who hustle.", "Coisas boas acontecem pra quem corre atrás."),
q("Respect is earned, not given.", "Respeito se conquista, não se dá."),
q("Throw me to the wolves and I'll return leading the pack.", "Me jogue aos lobos e eu volto liderando a alcateia."),
q("I'm rare, and worth the wait.", "Eu sou raro, e valho a espera."),
],
"vida": [
q("Life is tough, but so are you.", "A vida é dura, mas você também é."),
q("Enjoy the journey, not just the destination.", "Aproveite a jornada, não só o destino."),
q("Every day is a fresh start.", "Todo dia é um novo começo."),
q("Life is short. Make it sweet.", "A vida é curta. Faça dela algo doce."),
q("Collect moments, not things.", "Colecione momentos, não coisas."),
q("Life happens outside your comfort zone.", "A vida acontece fora da sua zona de conforto."),
q("Do what makes your soul shine.", "Faça o que faz sua alma brilhar."),
q("Grow through what you go through.", "Cresça através do que você atravessa."),
q("Be present. It's a gift.", "Esteja presente. É um presente."),
q("The best is yet to come.", "O melhor ainda está por vir."),
q("Life is better when you're laughing.", "A vida é melhor quando você está rindo."),
q("Take the risk or lose the chance.", "Corra o risco ou perca a chance."),
q("Some of the best chapters haven't been written yet.", "Alguns dos melhores capítulos ainda não foram escritos."),
q("You only live once, but if you do it right, once is enough.", "Você só vive uma vez, mas se viver bem, uma vez basta."),
q("Make peace with your past so it won't ruin your present.", "Faça as pazes com o passado pra ele não estragar o presente."),
q("Life isn't about waiting for the storm to pass.", "A vida não é sobre esperar a tempestade passar."),
q("Happiness looks good on you.", "A felicidade fica bem em você."),
q("Turn the page, don't close the book.", "Vire a página, não feche o livro."),
q("Everything you need is already inside you.", "Tudo o que você precisa já está dentro de você."),
q("Life is a beautiful ride.", "A vida é um passeio lindo."),
q("Slow down and enjoy the view.", "Desacelere e aproveite a vista."),
q("The good life is a process, not a destination.", "A boa vida é um processo, não um destino."),
q("Be happy for this moment. This moment is your life.", "Seja feliz por este momento. Este momento é a sua vida."),
q("Choose people who choose you.", "Escolha pessoas que escolhem você."),
q("Live simply, dream big.", "Viva de forma simples, sonhe grande."),
],
"superacao": [
q("You survived 100% of your worst days.", "Você sobreviveu a 100% dos seus piores dias."),
q("Storms make trees take deeper roots.", "As tempestades fazem as árvores criarem raízes mais profundas."),
q("What doesn't kill you makes you stronger.", "O que não te mata te fortalece."),
q("Scars are proof that you healed.", "Cicatrizes são a prova de que você se curou."),
q("Rock bottom became the foundation I rebuilt my life on.", "O fundo do poço virou a base sobre a qual reconstruí minha vida."),
q("You are stronger than you think.", "Você é mais forte do que pensa."),
q("Tough times never last, but tough people do.", "Tempos difíceis não duram, mas pessoas fortes sim."),
q("Every setback is a setup for a comeback.", "Cada revés é a preparação para uma volta por cima."),
q("Keep your head up, your story isn't over.", "Mantenha a cabeça erguida, sua história não acabou."),
q("You didn't survive all of that for nothing.", "Você não sobreviveu a tudo aquilo à toa."),
q("Healing takes time, and that's okay.", "A cura leva tempo, e tudo bem."),
q("Fall down seven times, get up eight.", "Caia sete vezes, levante oito."),
q("The strongest people are forged in the hardest fires.", "As pessoas mais fortes são forjadas nos fogos mais difíceis."),
q("Your comeback is loading.", "Sua volta por cima está carregando."),
q("Believe in the person you're becoming.", "Acredite na pessoa que você está se tornando."),
q("You are allowed to start over as many times as you need.", "Você tem o direito de recomeçar quantas vezes precisar."),
q("Strength grows in the moments you think you can't go on.", "A força cresce nos momentos em que você acha que não aguenta mais."),
q("This too shall pass.", "Isso também vai passar."),
q("From the ashes, I rise.", "Das cinzas, eu me levanto."),
q("You've got this, even when it feels like you don't.", "Você consegue, mesmo quando parece que não."),
q("Turn the pain into power.", "Transforme a dor em força."),
q("Little by little, one travels far.", "Pouco a pouco, se vai longe."),
q("Courage doesn't always roar.", "A coragem nem sempre ruge."),
q("You bend, but you don't break.", "Você se dobra, mas não se quebra."),
q("The best view comes after the hardest climb.", "A melhor vista vem depois da subida mais difícil."),
],
"tristes": [
q("Sometimes the strongest people are the most tired.", "Às vezes as pessoas mais fortes são as mais cansadas."),
q("I miss the person I used to be.", "Sinto falta da pessoa que eu costumava ser."),
q("Not all wounds are visible.", "Nem todas as feridas são visíveis."),
q("I'm tired of being strong all the time.", "Estou cansado de ser forte o tempo todo."),
q("It's okay to not be okay.", "Tudo bem não estar bem."),
q("The saddest people smile the brightest.", "As pessoas mais tristes são as que sorriem mais."),
q("Some goodbyes hurt forever.", "Alguns adeuses doem para sempre."),
q("I hide my tears behind my smile.", "Escondo minhas lágrimas atrás do meu sorriso."),
q("Missing you comes in waves.", "A saudade de você vem em ondas."),
q("Sometimes I just need someone to understand.", "Às vezes só preciso de alguém que entenda."),
q("Broken crayons still color.", "Giz de cera quebrado ainda colore."),
q("My silence says everything I can't.", "Meu silêncio diz tudo o que eu não consigo."),
q("I'm slowly learning to let go.", "Estou aprendendo devagar a deixar ir."),
q("Even the darkest night will end.", "Até a noite mais escura vai acabar."),
q("Feelings are much like waves; we can't stop them from coming.", "Sentimentos são como ondas; não podemos impedi-los de vir."),
q("Tears are words the heart can't say.", "Lágrimas são palavras que o coração não consegue dizer."),
q("I let go, but it still hurts.", "Eu deixei ir, mas ainda dói."),
q("The heart was made to be broken and to heal.", "O coração foi feito pra se partir e se curar."),
q("It's hard to forget someone who gave you so much to remember.", "É difícil esquecer alguém que te deu tanto pra lembrar."),
q("I'm okay is the biggest lie I tell.", "'Estou bem' é a maior mentira que eu conto."),
q("Grief is love with nowhere to go.", "O luto é o amor sem lugar pra ir."),
q("Some days I just fake a smile.", "Alguns dias eu só finjo um sorriso."),
q("Behind my calm there's a storm you don't see.", "Por trás da minha calma há uma tempestade que você não vê."),
q("Letting go is the hardest kind of love.", "Deixar ir é o tipo de amor mais difícil."),
q("Even flowers grow through the rain.", "Até as flores crescem sob a chuva."),
],
"status": [
q("Currently: creating my own sunshine.", "Atualmente: criando o meu próprio sol."),
q("Living my best life.", "Vivendo a minha melhor vida."),
q("Too busy watering my own grass.", "Ocupado demais regando a minha própria grama."),
q("Making memories all over the place.", "Fazendo memórias por todo lugar."),
q("Sunsets and good vibes.", "Pôr do sol e boas energias."),
q("Doing me, better than ever.", "Sendo eu mesmo, melhor do que nunca."),
q("Note to self: you're doing great.", "Recado pra mim: você está indo muito bem."),
q("Blessed and thankful.", "Abençoado e grato."),
q("Chapter loading… stay tuned.", "Capítulo carregando… fique ligado."),
q("Weekend mood: on.", "Modo fim de semana: ativado."),
q("Grateful heart, happy life.", "Coração grato, vida feliz."),
q("Coffee in one hand, confidence in the other.", "Café numa mão, confiança na outra."),
q("Just a soul chasing sunsets.", "Só uma alma perseguindo pores do sol."),
q("Life update: still glowing.", "Atualização de vida: ainda brilhando."),
q("Smiling because it happened.", "Sorrindo porque aconteceu."),
q("Feeling myself, no apologies.", "Me sentindo bem, sem pedir desculpas."),
q("Good energy is contagious.", "A energia boa é contagiante."),
q("Here for a good time and a long time.", "Aqui pra um bom tempo e um longo tempo."),
q("Choosing happiness on repeat.", "Escolhendo a felicidade no repeat."),
q("New week, new goals.", "Semana nova, metas novas."),
q("Manifesting good things.", "Manifestando coisas boas."),
q("Just vibes and sunshine.", "Só boas vibes e sol."),
q("Focused on my glow up.", "Focado na minha evolução."),
q("Adventure is calling.", "A aventura está chamando."),
q("Life tastes better with gratitude.", "A vida tem gosto melhor com gratidão."),
],
"sabedoria": [
q("Be patient. Everything comes to you at the right time.", "Tenha paciência. Tudo chega a você no momento certo."),
q("The quieter you become, the more you can hear.", "Quanto mais quieto você fica, mais consegue ouvir."),
q("What you seek is seeking you.", "O que você procura também está procurando você."),
q("Do good and good will come to you.", "Faça o bem e o bem virá até você."),
q("A calm mind brings inner strength.", "Uma mente calma traz força interior."),
q("Don't judge each day by the harvest you reap.", "Não julgue cada dia pela colheita que você faz."),
q("The wound is the place where the light enters you.", "A ferida é o lugar por onde a luz entra em você."),
q("Peace begins with a smile.", "A paz começa com um sorriso."),
q("You cannot pour from an empty cup.", "Você não pode servir de um copo vazio."),
q("Nature does not hurry, yet everything is accomplished.", "A natureza não tem pressa, e ainda assim tudo se realiza."),
q("The best time to plant a tree was yesterday. The second best is now.", "A melhor hora de plantar uma árvore foi ontem. A segunda melhor é agora."),
q("Let go of what you can't control.", "Solte o que você não pode controlar."),
q("Your peace is more important than being right.", "Sua paz é mais importante do que ter razão."),
q("Wisdom begins in wonder.", "A sabedoria começa no espanto."),
q("The mind is everything. What you think you become.", "A mente é tudo. Você se torna aquilo que pensa."),
q("Silence is sometimes the best answer.", "O silêncio às vezes é a melhor resposta."),
q("Fall in love with taking care of yourself.", "Apaixone-se por cuidar de si mesmo."),
q("Simplicity is the ultimate sophistication.", "A simplicidade é a máxima sofisticação."),
q("Gratitude turns what we have into enough.", "A gratidão transforma o que temos em suficiente."),
q("Be like water: gentle and unstoppable.", "Seja como a água: suave e imparável."),
q("The soul always knows what to do to heal itself.", "A alma sempre sabe o que fazer pra se curar."),
q("Doing nothing is sometimes doing everything.", "Não fazer nada às vezes é fazer tudo."),
q("Respect yourself enough to walk away from what no longer serves you.", "Respeite-se o suficiente pra se afastar do que não te serve mais."),
q("Grow at your own pace.", "Cresça no seu próprio ritmo."),
q("Every ending is a new beginning.", "Todo fim é um novo começo."),
],
}

index = []
total = 0
for cid, name, emoji, grad in CATS:
    items = DATA[cid]
    with open(os.path.join(BASE, cid + ".json"), "w", encoding="utf-8") as f:
        json.dump(items, f, ensure_ascii=False, indent=2)
    total += len(items)
    index.append({"id": cid, "name": name, "emoji": emoji, "gradient": grad, "premium": False})

with open(os.path.join(BASE, "index.json"), "w", encoding="utf-8") as f:
    json.dump(index, f, ensure_ascii=False, indent=2)

print("Categorias:", len(CATS), "| Total frases:", total)
for cid, name, *_ in CATS:
    print(f"  {name}: {len(DATA[cid])}")
